### ISSUE TITLE
participate in the project.

### ISSUE THREAD

**Issue by cbsistem** [DrHank/DelphiWeb#1]
Hello! I would like to participate in the project.

**Comment by DrHank** [comment]
Hello. I am happy to know. I am finishing the basic implementation, there are many changes that are not in the repository yet. During the next week I will contact you.

**Comment by cbsistem** [comment]
very good commit.  I change to compatible Lazarus IDE.

**Comment by DrHank** [comment]
Please do not change yet. I need to change the core to Indy because work with unblock sockets in this project is very difficult.

**Comment by cbsistem** [comment]
Ola Delcio, entre em contato no meu skype eu posso ajudar.
acho indy meio problematico quando sai novas atualizações.

Qual o problema que você esta enfrentando?
